<a href="https://colab.research.google.com/github/Kartikey9936/Classical-ML/blob/main/API_to_JSON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import requests

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=219e144f050ec31234f3f1d4c46b1915&language=en-US&page=1')

In [ ]:
data = response.json()['results']

In [ ]:
df = pd.DataFrame(data)
df.shape

(20, 15)

In [ ]:
df[['id','title','overview','release_date','popularity','vote_average']]

,id,title,overview,release_date,popularity,vote_average
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,302.0875,9.000
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,73.8924,8.721
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,47.8459,8.687
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,351.8456,8.635
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,29.3618,8.571
5,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,30.7355,8.569
6,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,23.1122,8.562
7,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,35.9329,8.500
8,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,48.8874,8.531
9,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,87.7660,8.534
10,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,19.0353,8.500
11,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,31.0256,8.506
12,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,44.5548,8.498
13,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,13.6161,8.500
14,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,39.0846,8.494
15,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,36.8495,8.500
16,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,29.4314,8.479
17,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,81.0831,8.475
18,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,22.9763,8.500
19,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,34.1886,8.465

In [ ]:
df = pd.DataFrame() #it will create a empty

In [ ]:
for i in range(1,500):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=219e144f050ec31234f3f1d4c46b1915&language=en-US&page={}'.format(i))
    response_data = response.json()

In [ ]:
df

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",302.0875,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,9.000,1430.0
1,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,73.8924,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.721,30415.0
2,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",47.8459,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.687,22952.0
3,False,/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,351.8456,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.635,4223.0
4,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,29.3618,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,False,False,8.571,13911.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,NaN,NaN,NaN,339530,Tremors 5: Bloodlines,NaN,NaN,When Gummer is hired to capture a deadly creat...,2.2708,NaN,2015-10-06,NaN,NaN,5.554,NaN
29996,NaN,NaN,NaN,54054,One for the Money,NaN,NaN,An unemployed lingerie buyer convinces her bai...,1.7273,NaN,2012-01-26,NaN,NaN,5.554,NaN
29997,NaN,NaN,NaN,9879,Striptease,NaN,NaN,"Bounced from her job, Erin Grant needs money i...",5.3937,NaN,1996-06-28,NaN,NaN,5.554,NaN
29998,NaN,NaN,NaN,560144,Skylines,NaN,NaN,When a virus threatens to turn the now earth-d...,2.3910,NaN,2020-10-25,NaN,NaN,5.553,NaN
29999,NaN,NaN,NaN,520360,King of Thieves,NaN,NaN,"London, England, April 2015. Brian Reader, a r...",2.1936,NaN,2018-09-04,NaN,NaN,5.553,NaN